#!/usr/bin/env bash
# deploy.sh
# One-command deployment for the XQORA demo application.
#
# Usage:
#   ./scripts/deploy.sh
#
# Steps performed automatically:
#   1. Validate the environment (delegates to setup.sh)
#   2. Build the application (docker image)
#   3. Create Docker images
#   4. Start required containers
#   5. Configure networking
#   6. Perform health checks
#   7. Confirm successful deployment (or trigger rollback + report failure)
#
# On success: prints "DEPLOYMENT SUCCESSFUL" and writes a deployment report.
# On failure: prints "DEPLOYMENT FAILED" with the reason, triggers rollback.sh,
#             and writes a deployment report noting the failure and rollback status.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"
log_init "deploy"

HEALTHCHECK_RETRIES=10
HEALTHCHECK_INTERVAL=3
REPORT_FILE="${LOG_DIR}/deployment-report-${RUN_ID}.txt"
FAIL_REASON=""

fail_deploy() {
  FAIL_REASON="$1"
  log_error "$FAIL_REASON"
  echo ""
  echo -e "${C_RED}${C_BOLD}DEPLOYMENT FAILED${C_RESET}"
  echo -e "${C_RED}Reason: ${FAIL_REASON}${C_RESET}"

  log_step "Triggering automated rollback"
  ROLLBACK_STATUS="not attempted"
  if [ -x "${SCRIPT_DIR}/rollback.sh" ]; then
    if "${SCRIPT_DIR}/rollback.sh" --reason "deploy failure: ${FAIL_REASON}"; then
      ROLLBACK_STATUS="succeeded"
    else
      ROLLBACK_STATUS="failed"
    fi
  else
    log_warn "rollback.sh not found or not executable; skipping automatic rollback."
    ROLLBACK_STATUS="skipped (rollback.sh unavailable)"
  fi

  write_report "DEPLOYMENT FAILED" "$FAIL_REASON" "$ROLLBACK_STATUS"
  state_write "FAILED" "${APP_VERSION:-unknown}" "$FAIL_REASON"
  exit 1
}

write_report() {
  local status="$1" reason="$2" rollback_status="$3"
  {
    echo "XQORA Deployment Report"
    echo "========================"
    echo "Date/Time (UTC):     $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    echo "Version/Build:       ${APP_VERSION:-unknown}"
    echo "Deployment Status:   ${status}"
    echo "Health-check Result: ${HEALTH_RESULT:-N/A}"
    echo "Errors:              ${reason:-none}"
    echo "Rollback Status:     ${rollback_status:-N/A}"
    echo ""
    echo "Full run log: ${CURRENT_LOG_FILE}"
  } | tee "$REPORT_FILE" >> "$CURRENT_LOG_FILE"
  log_info "Deployment report written to ${REPORT_FILE}"
}

# ---------------------------------------------------------------------------
log_step "1/7  Validating environment"
if ! "${SCRIPT_DIR}/setup.sh"; then
  fail_deploy "Environment validation failed (see setup logs). Run ./scripts/setup.sh directly for details."
fi

# Load config generated by setup.sh
if [ -f "$ENV_FILE" ]; then
  set -a; source "$ENV_FILE"; set -a
else
  fail_deploy "Missing .env file at ${ENV_FILE}; environment setup did not complete."
fi

COMPOSE="$(docker_compose_cmd)"
if [ -z "$COMPOSE" ]; then
  fail_deploy "Docker Compose not available."
fi

# Snapshot current running version (for rollback) before touching anything
PREVIOUS_VERSION=""
if [ -f "$STATE_FILE" ]; then
  PREVIOUS_VERSION="$(state_read_field version)"
fi
if [ -n "$PREVIOUS_VERSION" ] && docker image inspect "${APP_NAME}:${PREVIOUS_VERSION}" >/dev/null 2>&1; then
  BACKUP_TAG="${BACKUP_DIR}/last-good-version.txt"
  echo "$PREVIOUS_VERSION" > "$BACKUP_TAG"
  log_info "Recorded previous working version for rollback: ${PREVIOUS_VERSION}"
fi

# ---------------------------------------------------------------------------
log_step "2/7  Building the application"
cd "$PROJECT_ROOT" || fail_deploy "Cannot cd into project root ${PROJECT_ROOT}"
log_info "Building with APP_VERSION=${APP_VERSION}, HOST_PORT=${HOST_PORT}"

# ---------------------------------------------------------------------------
log_step "3/7  Creating Docker image(s)"
if ! $COMPOSE build 2>>"$CURRENT_LOG_FILE"; then
  fail_deploy "Docker image build failed. See ${CURRENT_LOG_FILE} for details."
fi
log_ok "Docker image built: ${APP_NAME}:${APP_VERSION}"

# ---------------------------------------------------------------------------
log_step "4/7  Starting required containers"
if ! $COMPOSE up -d --remove-orphans 2>>"$CURRENT_LOG_FILE"; then
  fail_deploy "Failed to start containers via docker compose up."
fi
log_ok "Container(s) started"

# ---------------------------------------------------------------------------
log_step "5/7  Configuring networking"
if docker network inspect xqora-net >/dev/null 2>&1; then
  log_ok "Network 'xqora-net' is configured"
else
  fail_deploy "Expected Docker network 'xqora-net' was not created."
fi

if port_in_use "$HOST_PORT"; then
  log_ok "Service is bound and listening on port ${HOST_PORT}"
else
  fail_deploy "Port ${HOST_PORT} is not accessible after container start."
fi

# ---------------------------------------------------------------------------
log_step "6/7  Performing health checks"
HEALTH_URL="http://localhost:${HOST_PORT}/health"
HEALTH_RESULT="unknown"
ATTEMPT=1
HEALTHY=0
while [ "$ATTEMPT" -le "$HEALTHCHECK_RETRIES" ]; do
  log_info "Health check attempt ${ATTEMPT}/${HEALTHCHECK_RETRIES} -> ${HEALTH_URL}"
  if command_exists curl; then
    RESP="$(curl -fsS "$HEALTH_URL" 2>>"$CURRENT_LOG_FILE")"
  else
    RESP="$(wget -qO- "$HEALTH_URL" 2>>"$CURRENT_LOG_FILE")"
  fi
  if [ -n "$RESP" ] && echo "$RESP" | grep -q '"status":"UP"\|"status": "UP"'; then
    HEALTHY=1
    HEALTH_RESULT="UP - ${RESP}"
    log_ok "Health-check endpoint responding: UP"
    break
  fi
  sleep "$HEALTHCHECK_INTERVAL"
  ATTEMPT=$((ATTEMPT + 1))
done

if [ "$HEALTHY" -ne 1 ]; then
  HEALTH_RESULT="DOWN / no valid response after ${HEALTHCHECK_RETRIES} attempts"
  fail_deploy "Health-check endpoint did not report healthy status after ${HEALTHCHECK_RETRIES} attempts."
fi

# Verify container is actually running (all required services operational)
CONTAINER_STATE="$(docker inspect -f '{{.State.Status}}' "$APP_NAME" 2>/dev/null || echo "missing")"
if [ "$CONTAINER_STATE" != "running" ]; then
  fail_deploy "Application container is not in 'running' state (state: ${CONTAINER_STATE})."
fi
log_ok "Application container is running (state: ${CONTAINER_STATE})"

# ---------------------------------------------------------------------------
log_step "7/7  Confirming successful deployment"
docker tag "${APP_NAME}:${APP_VERSION}" "${APP_NAME}:last-good" 2>>"$CURRENT_LOG_FILE" || true
state_write "SUCCESS" "$APP_VERSION" "none"
write_report "DEPLOYMENT SUCCESSFUL" "none" "N/A"

echo ""
echo -e "${C_GREEN}${C_BOLD}DEPLOYMENT SUCCESSFUL${C_RESET}"
echo -e "  App URL:      http://localhost:${HOST_PORT}"
echo -e "  Health URL:   ${HEALTH_URL}"
echo -e "  Version:      ${APP_VERSION}"
echo -e "  Report:       ${REPORT_FILE}"
exit 0
